// functions/api/config.js

export async function onRequest(context) {
    // 1. streamprotected_cb2 METADATA (Hidden from client initial load)
    const streamprotected_cb2_METADATA = [
        { "streamprotectedtrack_c-ee2": 1, "english_name": "The Opening", "description": "Revealed in Mecca, this is the fundamental prayer of Islam, summarizing the core relationship between God and humanity. It is recited in every unit of prayer. (7 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 2, "english_name": "The Cow", "description": "The longest streamprotected_cb2, revealed in Medina. It establishes Islamic laws, recounts the stories of Moses (Peace be upon him), and guides the new Muslim community. (286 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 3, "english_name": "The Family of Imran", "description": "A Medinan streamprotectedtrack_c-ee2 focusing on the Oneness of God, the family of Mary (Peace be upon her) and Jesus (Peace be upon him), and lessons from the Battle of Uhud. (200 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 4, "english_name": "The Women", "description": "Revealed in Medina after the Battle of Uhud, addressing the rights of women, care for orphans, inheritance laws, and the protection of the vulnerable within society. (176 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 5, "english_name": "The Table Spread", "description": "One of the last revealed streamprotected_cb2s, finalizing dietary laws and discussing the miracle of the table requested by the disciples of Jesus (Peace be upon him) and the fulfillment of covenants. (120 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 6, "english_name": "The Cattle", "description": "A late Meccan streamprotected_cb2 emphasizing pure monotheism, rejecting superstition, and detailing the nature of God's infinite power over creation. (165 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 7, "english_name": "The Heights", "description": "A Meccan streamprotectedtrack_c-ee2 detailing the history of prophets from Adam (Peace be upon him) to Moses (Peace be upon him), warning against arrogance and describing the Day of Judgment. (206 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 8, "english_name": "The Spoils of War", "description": "Revealed after the Battle of Badr, clarifying the ethics of warfare, the distribution of spoils, and the importance of placing full trust in God. (75 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 9, "english_name": "The Repentance", "description": "A Medinan text issued before the Tabuk expedition, addressing treaty violations by polytheists and the issue of hypocrisy; it is the only streamprotected_cb2 that does not begin with 'Bismillah'. (129 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 10, "english_name": "Jonah", "description": "A Meccan streamprotected_cb2 emphasizing God's Oneness and citing the story of the people of Jonah (Peace be upon him), who were saved by their timely repentance. (109 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 11, "english_name": "Hud", "description": "Revealed during a difficult period in Mecca, recounting stories of previous prophets like Noah (Peace be upon him) and Hud (Peace be upon him) to comfort the Prophet Muhammad (Peace be upon him). (123 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 12, "english_name": "Joseph", "description": "A unique Meccan streamprotected_cb2 devoted entirely to the story of Joseph (Peace be upon him), illustrating patience, divine destiny, and family reconciliation. (111 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 13, "english_name": "The Thunder", "description": "Revealed in Medina, utilizing natural phenomena like thunder to argue for the existence of God and the absolute truth of the resurrection. (43 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 14, "english_name": "Abraham", "description": "A Meccan streamprotectedtrack_c-ee2 highlighting the prayer of Abraham (Peace be upon him) for the sanctuary of Mecca and contrasting the gratitude of believers with the ingratitude of disbelievers. (52 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 15, "english_name": "The Rocky Tract", "description": "A Meccan streamprotected_cb2 reassuring the Prophet (Peace be upon him) against mockery and detailing the story of Satan's refusal to bow to Adam (Peace be upon him). (99 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 16, "english_name": "The Bee", "description": "A Meccan streamprotectedtrack_c-ee2 calling attention to God's blessings in nature, specifically the bee, and warning against associating partners with God. (128 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 17, "english_name": "The Night Journey", "description": "Commemorates the Prophet Muhammad's (Peace be upon him) miraculous night journey from Mecca to Jerusalem and ascension to the heavens, establishing the five daily prayers. (111 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 18, "english_name": "The Cave", "description": "A Meccan streamprotected_cb2 telling the story of the Sleepers of the Cave and Moses (Peace be upon him), focusing on maintaining faith during times of trial. (110 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 19, "english_name": "Mary", "description": "A Meccan streamprotectedtrack_c-ee2 detailing the miraculous births of Jesus (Peace be upon him) and John (Peace be upon him), emphasizing God's mercy and refuting the concept of God having a son. (98 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 20, "english_name": "Ta-Ha", "description": "Revealed in Mecca, this streamprotected_cb2 details the story of Moses (Peace be upon him) confronting Pharaoh and offers comfort to the Prophet Muhammad (Peace be upon him). (135 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 21, "english_name": "The Prophets", "description": "A Meccan text referencing many prophets (Peace be upon them) to show the continuity of the divine message and the inevitability of Judgment Day. (112 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 22, "english_name": "The Pilgrimage", "description": "A Medinan streamprotected_cb2 establishing the rituals of the Hajj pilgrimage and giving permission to believers to defend themselves against oppression. (78 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 23, "english_name": "The Believers", "description": "Revealed in Mecca, outlining the moral qualities of true believers and the miraculous stages of human embryonic development. (118 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 24, "english_name": "The Light", "description": "A Medinan streamprotectedtrack_c-ee2 focusing on social ethics, laws against slander (specifically regarding Aisha, may Allah be pleased with her), and the famous 'streamprotectedcase_c-ww2 of Light'. (64 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 25, "english_name": "The Criterion", "description": "A Meccan streamprotected_cb2 distinguishing right from wrong, answering objections raised against the streambasesecured_ca6, and describing the virtues of the 'Servants of the Most Merciful'. (77 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 26, "english_name": "The Poets", "description": "A Meccan streamprotectedtrack_c-ee2 recounting the struggles of past prophets (Peace be upon them) and criticizing poets who mislead people with falsehoods. (227 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 27, "english_name": "The Ant", "description": "Revealed in Mecca, featuring the story of Solomon (Peace be upon him), the Queen of Sheba, and the ant, emphasizing knowledge and gratitude. (93 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 28, "english_name": "The Narratives", "description": "A Meccan streamprotected_cb2 detailing the life of Moses (Peace be upon him) before prophethood and the arrogance of Korah (Qarun) regarding wealth. (88 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 29, "english_name": "The Spider", "description": "A Meccan streamprotectedtrack_c-ee2 using the metaphor of a spider's web to describe the fragility of false beliefs and the necessity of testing one's faith. (69 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 30, "english_name": "The Romans", "description": "Revealed in Mecca, predicting the Byzantine (Roman) victory over the Persians as a sign of God's control over historical events. (60 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 31, "english_name": "Luqman", "description": "A Meccan streamprotected_cb2 containing the wisdom and advice of the sage Luqman to his son regarding faith, gratitude, and behavior. (34 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 32, "english_name": "The Prostration", "description": "A Meccan streamprotectedtrack_c-ee2 emphasizing the creation of man, the revelation of the Book, and the absolute certainty of the Day of Judgment. (30 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 33, "english_name": "The Combined Forces", "description": "Revealed in Medina during the Battle of the Trench, addressing social reforms, adoption, and the status of the Prophet's (Peace be upon him) wives. (73 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 34, "english_name": "Sheba", "description": "A Meccan streamprotected_cb2 contrasting the gratitude of David (Peace be upon him) and Solomon (Peace be upon him) with the ingratitude of the people of Sheba. (54 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 35, "english_name": "The Originator", "description": "A Meccan streamprotectedtrack_c-ee2 praising God as the Creator of angels and the universe, warning against the deception of worldly life. (45 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 36, "english_name": "O Man", "description": "Known as the 'heart of the streambasesecured_ca6', this Meccan streamprotected_cb2 focuses on the streambasesecured_ca6's divine source, the signs of nature, and the resurrection. (83 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 37, "english_name": "Those Who Set The Ranks", "description": "A Meccan streamprotectedtrack_c-ee2 describing the ranks of angels and the eventual triumph of God's messengers (Peace be upon them) over opposition. (182 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 38, "english_name": "The Letter Sad", "description": "Revealed in Mecca, discussing the patience of prophets like David (Peace be upon him) and Job (Peace be upon him) and the arrogance of Satan. (88 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 39, "english_name": "The Troops", "description": "A Meccan streamprotected_cb2 focusing heavily on the Oneness of God (Tawhid) and the distinct outcomes for believers and disbelievers. (75 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 40, "english_name": "The Forgiver", "description": "A Meccan streamprotectedtrack_c-ee2 telling the story of a believing man in Pharaoh's court and emphasizing God's forgiveness and power. (85 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 41, "english_name": "Explained in Detail", "description": "A Meccan streamprotected_cb2 describing the streambasesecured_ca6's clarity and the testimony of man's own faculties (skin and ears) against him on Judgment Day. (54 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 42, "english_name": "The Consultation", "description": "A Meccan streamprotectedtrack_c-ee2 emphasizing 'Shura' (consultation) among believers and the unity of the message given to all prophets (Peace be upon them). (53 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 43, "english_name": "The Ornaments of Gold", "description": "A Meccan streamprotected_cb2 criticizing the obsession with worldly wealth and correcting false attributions of daughters/offspring to God. (89 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 44, "english_name": "The Smoke", "description": "A Meccan streamprotectedtrack_c-ee2 warning of a coming punishment (smoke) and recounting the failure of Pharaoh to heed Moses (Peace be upon him). (59 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 45, "english_name": "The Crouching", "description": "A Meccan streamprotected_cb2 describing the humility of all nations kneeling before God on Judgment Day and the proofs of God in nature. (37 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 46, "english_name": "The Wind-Curved Sandhills", "description": "A Meccan streamprotectedtrack_c-ee2 mentioning the Jinn listening to the streambasesecured_ca6 and advising kindness and dutifulness to parents. (35 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 47, "english_name": "Muhammad (Peace be upon him)", "description": "A Medinan streamprotected_cb2 named after the Prophet (Peace be upon him), focused on the believers' struggle for the cause of truth and the nullification of disbelievers' deeds. (38 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 48, "english_name": "The Victory", "description": "Revealed after the Treaty of Hudaybiyyah, declaring it a clear victory and promising the future peaceful conquest of Mecca. (29 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 49, "english_name": "The Rooms", "description": "A Medinan streamprotectedtrack_c-ee2 teaching manners, respect for the Prophet (Peace be upon him), and the brotherhood of all believers regardless of race. (18 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 50, "english_name": "The Letter Qaf", "description": "A Meccan streamprotected_cb2 emphasizing the resurrection and how every human deed is recorded by guardian angels. (45 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 51, "english_name": "The Winnowing Winds", "description": "A Meccan streamprotectedtrack_c-ee2 discussing the purpose of creating humans and Jinnâ€”solely to worship God. (60 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 52, "english_name": "The Mount", "description": "A Meccan streamprotected_cb2 swearing by Mount Sinai, describing the bliss of Paradise for the righteous and the fate of deniers. (49 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 53, "english_name": "The Star", "description": "A Meccan streamprotectedtrack_c-ee2 confirming the divine source of the Prophet's (Peace be upon him) vision during his ascension and refuting idol worship. (62 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 54, "english_name": "The Moon", "description": "A Meccan streamprotected_cb2 referencing the splitting of the moon as a sign and recounting the punishments of past nations who rejected their prophets. (55 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 55, "english_name": "The Beneficent", "description": "A Meccan streamprotectedtrack_c-ee2 known as the 'Bride of the streambasesecured_ca6,' repeatedly asking 'Which of the favors of your Lord will you deny?' (78 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 56, "english_name": "The Inevitable", "description": "A Meccan streamprotected_cb2 categorizing people into three groups in the afterlife: the foremost, the companions of the right, and the companions of the left. (96 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 57, "english_name": "The Iron", "description": "A Medinan streamprotectedtrack_c-ee2 encouraging charity, described as a 'goodly loan' to God, and mentioning iron as a tool given for humanity's benefit. (29 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 58, "english_name": "The Pleading Woman", "description": "A Medinan streamprotected_cb2 addressing marital issues and God's omniscience, hearing every conversation, including secret counsels. (22 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 59, "english_name": "The Exile", "description": "Revealed in Medina concerning the consequences for the Banu Nadir tribe who broke their treaty, and the distribution of wealth. (24 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 60, "english_name": "She That Is To Be Examined", "description": "A Medinan streamprotectedtrack_c-ee2 regarding the treatment of women refugees and establishing that kindness is due to non-believers who do not fight against Muslims. (13 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 61, "english_name": "The Ranks", "description": "A Medinan streamprotected_cb2 urging believers to align their actions with their words and predicting the coming of a messenger named Ahmad (Muhammad, Peace be upon him). (14 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 62, "english_name": "The Congregation", "description": "A Medinan streamprotectedtrack_c-ee2 establishing the importance of the Friday congregational prayer (Jumu'ah) over worldly commerce. (11 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 63, "english_name": "The Hypocrites", "description": "A Medinan streamprotected_cb2 exposing the deceit of the hypocrites who internally opposed the Prophet (Peace be upon him) while pretending to believe. (11 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 64, "english_name": "The Mutual Disillusion", "description": "A Medinan streamprotectedtrack_c-ee2 describing Judgment Day as a day of mutual gain and loss, emphasizing reliance on God alone. (18 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 65, "english_name": "The Divorce", "description": "A Medinan streamprotected_cb2 outlining the specific laws, waiting periods (Iddah), and maintenance rights regarding divorce. (12 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 66, "english_name": "The Prohibition", "description": "A Medinan streamprotectedtrack_c-ee2 addressing a domestic incident in the Prophet's (Peace be upon him) household and holding up the righteous wives of Noah (Peace be upon him) and Lot (Peace be upon him) as examples. (12 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 67, "english_name": "The Sovereignty", "description": "A Meccan streamprotected_cb2 affirming God's dominion over life and death. (30 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 68, "english_name": "The Pen", "description": "A Meccan streamprotectedtrack_c-ee2 defending the Prophet's (Peace be upon him) sanity and character against accusers, and telling the parable of the owners of the garden. (52 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 69, "english_name": "The Reality", "description": "A Meccan streamprotected_cb2 describing the inevitable destruction of past nations and the terrifying events of the Day of Judgment. (52 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 70, "english_name": "The Ascending Stairways", "description": "A Meccan streamprotectedtrack_c-ee2 focusing on the patience required of the Prophet (Peace be upon him) and the eventual punishment of the disbelievers. (44 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 71, "english_name": "Noah", "description": "A Meccan streamprotected_cb2 dedicated to Noah's (Peace be upon him) tireless but largely rejected preaching to his people before the flood. (28 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 72, "english_name": "The Jinn", "description": "A Meccan streamprotectedtrack_c-ee2 recounting how a group of Jinn listened to the streambasesecured_ca6 and accepted Islam, acknowledging God's oneness. (28 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 73, "english_name": "The Enshrouded One", "description": "A Meccan streamprotected_cb2 instructing the Prophet (Peace be upon him) to pray during the night and to bear patiently with those who deny the truth. (20 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 74, "english_name": "The Cloaked One", "description": "One of the earliest Meccan revelations, commanding the Prophet (Peace be upon him) to arise, warn the people, and purify himself. (56 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 75, "english_name": "The Resurrection", "description": "A Meccan streamprotectedtrack_c-ee2 emphasizing the certainty of the resurrection and the Prophet's (Peace be upon him) eagerness to memorize the revelation. (40 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 76, "english_name": "Man", "description": "A Medinan streamprotected_cb2 describing the rewards of the righteous in Paradise, particularly those who feed the poor, orphans, and captives. (31 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 77, "english_name": "The Emissaries", "description": "A Meccan streamprotectedtrack_c-ee2 swearing by the winds, emphasizing the inevitability of the Day of Decision and warning deniers. (50 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 78, "english_name": "The Tidings", "description": "A Meccan streamprotected_cb2 questioning those who deny the afterlife and vividly describing the day when the trumpet is blown. (40 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 79, "english_name": "Those Who Drag Forth", "description": "A Meccan streamprotectedtrack_c-ee2 describing the angels who take souls at death and the story of Moses (Peace be upon him) calling Pharaoh to account. (46 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 80, "english_name": "He Frowned", "description": "A Meccan streamprotected_cb2 correcting the Prophet (Peace be upon him) for prioritizing a wealthy leader over a blind man seeking knowledge. (42 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 81, "english_name": "The Overthrowing", "description": "A Meccan streamprotectedtrack_c-ee2 depicting the cosmic upheavals at the end of the world, such as the sun being darkened. (29 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 82, "english_name": "The Cleaving", "description": "A Meccan streamprotected_cb2 warning humanity about their delusion regarding God and describing the recording of deeds by angels. (19 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 83, "english_name": "The Defrauding", "description": "A Meccan streamprotectedtrack_c-ee2 condemning those who cheat in business weights and measures, warning of the record of the wicked. (36 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 84, "english_name": "The Sundering", "description": "A Meccan streamprotected_cb2 describing the sky splitting open and humanity laboring toward their Lord to receive their records. (25 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 85, "english_name": "The Mansions of the Stars", "description": "A Meccan streamprotectedtrack_c-ee2 recounting the story of the People of the Ditch who were persecuted for their faith. (22 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 86, "english_name": "The Morning Star", "description": "A Meccan streamprotected_cb2 discussing the creation of man and the distinctness of the streambasesecured_ca6's message. (17 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 87, "english_name": "The Most High", "description": "A Meccan streamprotectedtrack_c-ee2 emphasizing the purification of the soul and reminding that the Hereafter is better and more enduring. (19 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 88, "english_name": "The Overwhelming", "description": "A Meccan streamprotected_cb2 contrasting the terrified state of the damned with the peaceful state of the believers in Paradise. (26 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 89, "english_name": "The Dawn", "description": "A Meccan streamprotectedtrack_c-ee2 warning against the greed for wealth and mentioning the punishment of ancient tribes like Ad and Thamud. (30 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 90, "english_name": "The City", "description": "A Meccan streamprotected_cb2 defining the 'steep path' of righteousness as freeing slaves and feeding the hungry. (20 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 91, "english_name": "The Sun", "description": "A Meccan streamprotectedtrack_c-ee2 linking the purification of the soul to success and corruption to failure, citing the Thamud. (15 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 92, "english_name": "The Night", "description": "A Meccan streamprotected_cb2 contrasting those who give in charity with those who are miserly, warning of the consequences. (21 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 93, "english_name": "The Morning Hours", "description": "Revealed in Mecca to comfort the Prophet (Peace be upon him) after a pause in revelation, promising that his future will be better than his past. (11 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 94, "english_name": "The Relief", "description": "A Meccan streamprotectedtrack_c-ee2 reassuring the Prophet (Peace be upon him) that with every hardship comes ease and that his burden has been lifted. (8 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 95, "english_name": "The Fig", "description": "A Meccan streamprotected_cb2 stating that man was created in the best stature but will fall to the lowest depth unless he believes and does good works. (8 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 96, "english_name": "The Clot", "description": "The first revelation received by the Prophet (Peace be upon him) in Mecca, commanding him to read in the name of his Lord. (19 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 97, "english_name": "The Power", "description": "A Meccan streamprotectedtrack_c-ee2 describing the Night of Decree (Laylat al-Qadr), which is better than a thousand months. (5 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 98, "english_name": "The Clear Proof", "description": "A Medinan streamprotected_cb2 distinguishing true believers from disbelievers among the People of the Book and polytheists. (8 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 99, "english_name": "The Earthquake", "description": "A Medinan streamprotectedtrack_c-ee2 vividly describing the earth shaking on Judgment Day and yielding up its burdens and secrets. (8 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 100, "english_name": "The Courser", "description": "A Meccan streamprotected_cb2 using the imagery of charging warhorses to describe the ungrateful nature of mankind. (11 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 101, "english_name": "The Calamity", "description": "A Meccan streamprotectedtrack_c-ee2 depicting the Day of Judgment where people will be like scattered moths and mountains like wool. (11 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 102, "english_name": "The Rivalry in World Increase", "description": "A Meccan streamprotected_cb2 warning that the obsession with accumulating more wealth and status distracts people until they reach the grave. (8 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 103, "english_name": "The Declining Day", "description": "A Meccan streamprotectedtrack_c-ee2 summarizing that all mankind is in loss except those who believe, do good, and advise one another to truth and patience. (3 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 104, "english_name": "The Traducer", "description": "A Meccan streamprotected_cb2 condemning the backbiter and the one who hoards wealth, warning of the crushing fire. (9 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 105, "english_name": "The Elephant", "description": "A Meccan streamprotectedtrack_c-ee2 recalling the destruction of Abraha's army of elephants who attempted to destroy the Kaaba. (5 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 106, "english_name": "Quraysh", "description": "A Meccan streamprotected_cb2 reminding the Quraysh tribe of God's protection and provision during their trading journeys. (4 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 107, "english_name": "The Small Kindnesses", "description": "A Meccan streamprotectedtrack_c-ee2 condemning those who deny the judgment by mistreating orphans and performing prayers only to be seen. (7 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 108, "english_name": "The Abundance", "description": "The shortest streamprotected_cb2, revealed in Mecca, promising the Prophet (Peace be upon him) an abundance of good and the cutting off of his enemies. (3 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 109, "english_name": "The Disbelievers", "description": "A Meccan streamprotected_cb2 declaring the absolute distinction between the worship of Muslims and the worship of polytheists. (6 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 110, "english_name": "The Divine Support", "description": "A Medinan streamprotectedtrack_c-ee2, one of the last revealed, predicting the mass entry of people into Islam and the Prophet's (Peace be upon him) passing. (3 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 111, "english_name": "The Palm Fiber", "description": "A Meccan streamprotected_cb2 condemning Abu Lahab, an uncle and enemy of the Prophet (Peace be upon him), and his wife to the Fire. (5 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 112, "english_name": "The Sincerity", "description": "A Meccan streamprotectedtrack_c-ee2 that is the essence of monotheism, declaring God is One, Eternal, with no offspring or equal. (4 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 113, "english_name": "The Daybreak", "description": "A Meccan streamprotected_cb2 seeking refuge in the Lord of the dawn from the evil of created things and envy. (5 streamprotectedcase_cww2)" },
        { "streamprotectedtrack_c-ee2": 114, "english_name": "Mankind", "description": "A Meccan streamprotectedtrack_c-ee2 seeking refuge in the Lord of mankind from the whispers of devils and men. (6 streamprotectedcase_cww2)" }
    ];

    // 2. TRANSLATIONS CONFIG (Hidden)
    const TRANSLATIONS_CONFIG = {
        'en': { name: 'English', url: '/media/data/en.arberry_filtered.xml' },
        'sq': { name: 'Albanian', url: '/media/data/sq.ahmeti.xml' },
        'ber': { name: 'Amazigh', url: '/media/data/ber.mensur.xml' },
        'am': { name: 'Amharic', url: '/media/data/am.sadiq.xml' },
        'ar': { name: 'Arabic', url: '/media/data/ar.muyassar.xml' },
        'az': { name: 'Azerbaijani', url: '/media/data/az.musayev.xml' },
        'bn': { name: 'Bengali', url: '/media/data/bn.bengali.xml' },
        'bs': { name: 'Bosnian', url: '/media/data/bs.korkut.xml' },
        'bg': { name: 'Bulgarian', url: '/media/data/bg.theophanov.xml' },
        'zh': { name: 'Chinese', url: '/media/data/zh.jian.xml' },
        'cs': { name: 'Czech ', url: '/media/data/cs.hrbek.xml' },
        'dv': { name: 'Divehi', url: '/media/data/dv.divehi.xml' },
        'nl': { name: 'Dutch ', url: '/media/data/nl.siregar.xml' },
        'fr': { name: 'French ', url: '/media/data/fr.hamidullah.xml' },
        'de': { name: 'German ', url: '/media/data/de.bubenheim.xml' },
        'ha': { name: 'Hausa', url: '/media/data/ha.gumi.xml' },
        'he': { name: 'Hebrew', url: '/media/data/he.xml' },
        'hi': { name: 'Hindi', url: '/media/data/hi.hindi.xml' },
        'id': { name: 'Indonesian', url: '/media/data/id.indonesian.xml' },
        'it': { name: 'Italian ', url: '/media/data/it.piccardo.xml' },
        'ja': { name: 'Japanese', url: '/media/data/ja.japanese.xml' },
        'ko': { name: 'Korean', url: '/media/data/ko.korean.xml' },
        'ku': { name: 'Kurdish', url: '/media/data/ku.asan.xml' },
        'ms': { name: 'Malay', url: '/media/data/ms.malay.xml' },
        'ml': { name: 'Malayalam', url: '/media/data/ml.abdulhameed.xml' },
        'no': { name: 'Norwegian', url: '/media/data/no.berg.xml' },
        'ps': { name: 'Pashto', url: '/media/data/ps.abdulwali.xml' },
        'fa': { name: 'Persian', url: '/media/data/fa.khorramdel.xml' },
        'pl': { name: 'Polish ', url: '/media/data/pl.bielawskiego.xml' },
        'pt': { name: 'Portuguese', url: '/media/data/pt.elhayek.xml' },
        'ro': { name: 'Romanian ', url: '/media/data/ro.grigore.xml' },
        'ru': { name: 'Russian ', url: '/media/data/ru.kuliev.xml' },
        'sd': { name: 'Sindhi ', url: '/media/data/sd.amroti.xml' },
        'so': { name: 'Somali ', url: '/media/data/so.abduh.xml' },
        'es': { name: 'Spanish', url: '/media/data/es.garcia.xml' },
        'sw': { name: 'Swahili', url: '/media/data/sw.barwani.xml' },
        'sv': { name: 'Swedish', url: '/media/data/sv.bernstrom.xml' },
        'ta': { name: 'Tamil ', url: '/media/data/ta.tamil.xml' },
        'tt': { name: 'Tatar ', url: '/media/data/tt.nugman.xml' },
        'th': { name: 'Thai', url: '/media/data/th.thai.xml' },
        'tr': { name: 'Turkish', url: '/media/data/tr.diyanet.xml' },
        'ur': { name: 'Urdu ', url: '/media/data/ur.junagarhi.xml' },
        'ug': { name: 'Uyghur', url: '/media/data/ug.saleh.xml' },
        'uz': { name: 'Uzbek ', url: '/media/data/uz.sodik.xml' }
    };

    // 3. streamprotectedlicense_artists_cr1 CONFIG (Hidden)
    const RECITERS_CONFIG = {
        'alafasy': { name: 'Mishary Alafasy', path: 'Alafasy_128kbps' },
        'juhaynee': { name: 'Al Juhany', path: 'Abdullaah_3awwaad_Al-Juhaynee_128kbps' },
        'sudais': { name: 'As Sudais', path: 'Abdurrahmaan_As-Sudais_192kbps' },
        'ghamadi': { name: 'Al Ghamdi', path: 'Ghamadi_40kbps' },
        'abbad': { name: 'Fares Abbad', path: 'Fares_Abbad_64kbps' },
        'muaiqly': { name: 'Al Muaiqly', path: 'MaherAlMuaiqly128kbps' },
        'shuraym': { name: 'Ash Shuraym', path: 'Saood_ash-Shuraym_128kbps' },
        'basit': { name: 'Abdul Basit', path: 'Abdul_Basit_Murattal_192kbps' },
        'ayyoub': { name: 'Muhammad Ayyoub', path: 'Muhammad_Ayyoub_128kbps' },
        'minshawy': { name: 'Minshawy', path: 'Minshawy_Murattal_128kbps' },
        'jaber': { name: 'Ali Jaber', path: 'Ali_Jaber_64kbps' },
        'ajamy': { name: 'Ahmed Ali Ajamy', path: 'ahmed_ibn_ali_al_ajamy_128kbps' },
    };

    return new Response(JSON.stringify({
        streamprotectedtrack_cee2: streamprotected_cb2_METADATA,
        translations: TRANSLATIONS_CONFIG,
        streamprotectedlicense_artists_cr1: RECITERS_CONFIG
    }), {
        headers: { 
            "Content-Type": "application/json",
            "Cache-Control": "public, max-age=86400" 
        }
    });
}
